/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as identityRegistryImplV1Sol from "./IdentityRegistryImplV1.sol";
export { IdentityRegistry__factory } from "./IdentityRegistry__factory";
