/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable2StepUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2StepUpgradeable__factory>;
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UUPSUpgradeable__factory>;
    getContractFactory(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContextUpgradeable__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1822Proxiable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1967__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "ERC1967Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Proxy__factory>;
    getContractFactory(
      name: "ERC1967Utils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Utils__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "Address",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Address__factory>;
    getContractFactory(
      name: "MerkleProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleProof__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "PassportAirdropRoot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PassportAirdropRoot__factory>;
    getContractFactory(
      name: "Airdrop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Airdrop__factory>;
    getContractFactory(
      name: "IdentityVerificationHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityVerificationHub__factory>;
    getContractFactory(
      name: "IdentityVerificationHubImplV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityVerificationHubImplV1__factory>;
    getContractFactory(
      name: "IdentityVerificationHubStorageV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityVerificationHubStorageV1__factory>;
    getContractFactory(
      name: "IDscCircuitVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDscCircuitVerifier__factory>;
    getContractFactory(
      name: "IIdentityRegistryV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIdentityRegistryV1__factory>;
    getContractFactory(
      name: "IIdentityVerificationHubV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIdentityVerificationHubV1__factory>;
    getContractFactory(
      name: "IRegisterCircuitVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRegisterCircuitVerifier__factory>;
    getContractFactory(
      name: "IVcAndDiscloseCircuitVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVcAndDiscloseCircuitVerifier__factory>;
    getContractFactory(
      name: "CircuitAttributeHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CircuitAttributeHandler__factory>;
    getContractFactory(
      name: "Formatter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Formatter__factory>;
    getContractFactory(
      name: "IdentityRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityRegistry__factory>;
    getContractFactory(
      name: "IdentityRegistryImplV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityRegistryImplV1__factory>;
    getContractFactory(
      name: "IdentityRegistryStorageV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityRegistryStorageV1__factory>;
    getContractFactory(
      name: "AirdropToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AirdropToken__factory>;
    getContractFactory(
      name: "TestCircuitAttributeHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestCircuitAttributeHandler__factory>;
    getContractFactory(
      name: "TestFormatter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestFormatter__factory>;
    getContractFactory(
      name: "MockImplRoot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockImplRoot__factory>;
    getContractFactory(
      name: "ImplRoot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ImplRoot__factory>;
    getContractFactory(
      name: "ProxyRoot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProxyRoot__factory>;
    getContractFactory(
      name: "Verifier_vc_and_disclose",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_vc_and_disclose__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha1_ecdsa_brainpoolP256r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha1_ecdsa_brainpoolP256r1__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha1_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha1_rsa_65537_4096__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha256_ecdsa_brainpoolP256r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_brainpoolP256r1__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha256_ecdsa_secp256r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_secp256r1__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha256_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsa_65537_4096__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha256_rsapss_3_32_3072",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_3_32_3072__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha256_rsapss_65537_32_3072",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_3072__factory>;
    getContractFactory(
      name: "Verifier_dsc_sha256_rsapss_65537_32_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_4096__factory>;
    getContractFactory(
      name: "Verifier_register_sha1_sha1_sha1_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha1_sha1_sha1_rsa_65537_4096__factory>;
    getContractFactory(
      name: "Verifier_register_sha1_sha256_sha256_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha1_sha256_sha256_rsa_65537_4096__factory>;
    getContractFactory(
      name: "Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_rsa_3_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_3_4096__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_65537_4096__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048__factory>;
    getContractFactory(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072__factory>;
    getContractFactory(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1__factory>;
    getContractFactory(
      name: "Verifier_register_sha512_sha512_sha512_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_rsa_65537_4096__factory>;
    getContractFactory(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT3__factory>;

    getContractAt(
      name: "Ownable2StepUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2StepUpgradeable>;
    getContractAt(
      name: "OwnableUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "UUPSUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UUPSUpgradeable>;
    getContractAt(
      name: "ContextUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ContextUpgradeable>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1822Proxiable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1822Proxiable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "IERC1967",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1967>;
    getContractAt(
      name: "IBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "ERC1967Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Proxy>;
    getContractAt(
      name: "ERC1967Utils",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Utils>;
    getContractAt(
      name: "Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "Address",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Address>;
    getContractAt(
      name: "MerkleProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleProof>;
    getContractAt(
      name: "Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "PassportAirdropRoot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PassportAirdropRoot>;
    getContractAt(
      name: "Airdrop",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Airdrop>;
    getContractAt(
      name: "IdentityVerificationHub",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityVerificationHub>;
    getContractAt(
      name: "IdentityVerificationHubImplV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityVerificationHubImplV1>;
    getContractAt(
      name: "IdentityVerificationHubStorageV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityVerificationHubStorageV1>;
    getContractAt(
      name: "IDscCircuitVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDscCircuitVerifier>;
    getContractAt(
      name: "IIdentityRegistryV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIdentityRegistryV1>;
    getContractAt(
      name: "IIdentityVerificationHubV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIdentityVerificationHubV1>;
    getContractAt(
      name: "IRegisterCircuitVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRegisterCircuitVerifier>;
    getContractAt(
      name: "IVcAndDiscloseCircuitVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVcAndDiscloseCircuitVerifier>;
    getContractAt(
      name: "CircuitAttributeHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CircuitAttributeHandler>;
    getContractAt(
      name: "Formatter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Formatter>;
    getContractAt(
      name: "IdentityRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityRegistry>;
    getContractAt(
      name: "IdentityRegistryImplV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityRegistryImplV1>;
    getContractAt(
      name: "IdentityRegistryStorageV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityRegistryStorageV1>;
    getContractAt(
      name: "AirdropToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AirdropToken>;
    getContractAt(
      name: "TestCircuitAttributeHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestCircuitAttributeHandler>;
    getContractAt(
      name: "TestFormatter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestFormatter>;
    getContractAt(
      name: "MockImplRoot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockImplRoot>;
    getContractAt(
      name: "ImplRoot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ImplRoot>;
    getContractAt(
      name: "ProxyRoot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProxyRoot>;
    getContractAt(
      name: "Verifier_vc_and_disclose",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_vc_and_disclose>;
    getContractAt(
      name: "Verifier_dsc_sha1_ecdsa_brainpoolP256r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha1_ecdsa_brainpoolP256r1>;
    getContractAt(
      name: "Verifier_dsc_sha1_rsa_65537_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha1_rsa_65537_4096>;
    getContractAt(
      name: "Verifier_dsc_sha256_ecdsa_brainpoolP256r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_brainpoolP256r1>;
    getContractAt(
      name: "Verifier_dsc_sha256_ecdsa_secp256r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_secp256r1>;
    getContractAt(
      name: "Verifier_dsc_sha256_rsa_65537_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha256_rsa_65537_4096>;
    getContractAt(
      name: "Verifier_dsc_sha256_rsapss_3_32_3072",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_3_32_3072>;
    getContractAt(
      name: "Verifier_dsc_sha256_rsapss_65537_32_3072",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_3072>;
    getContractAt(
      name: "Verifier_dsc_sha256_rsapss_65537_32_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_4096>;
    getContractAt(
      name: "Verifier_register_sha1_sha1_sha1_rsa_65537_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha1_sha1_sha1_rsa_65537_4096>;
    getContractAt(
      name: "Verifier_register_sha1_sha256_sha256_rsa_65537_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha1_sha256_sha256_rsa_65537_4096>;
    getContractAt(
      name: "Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1>;
    getContractAt(
      name: "Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_rsa_3_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_3_4096>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_rsa_65537_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_65537_4096>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048>;
    getContractAt(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072>;
    getContractAt(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1>;
    getContractAt(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1>;
    getContractAt(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1>;
    getContractAt(
      name: "Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1>;
    getContractAt(
      name: "Verifier_register_sha512_sha512_sha512_rsa_65537_4096",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_rsa_65537_4096>;
    getContractAt(
      name: "PoseidonT3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT3>;

    deployContract(
      name: "Ownable2StepUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2StepUpgradeable>;
    deployContract(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUpgradeable>;
    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeable>;
    deployContract(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ContextUpgradeable>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Proxy>;
    deployContract(
      name: "ERC1967Utils",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Utils>;
    deployContract(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "Address",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "MerkleProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleProof>;
    deployContract(
      name: "Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "PassportAirdropRoot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PassportAirdropRoot>;
    deployContract(
      name: "Airdrop",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Airdrop>;
    deployContract(
      name: "IdentityVerificationHub",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityVerificationHub>;
    deployContract(
      name: "IdentityVerificationHubImplV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityVerificationHubImplV1>;
    deployContract(
      name: "IdentityVerificationHubStorageV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityVerificationHubStorageV1>;
    deployContract(
      name: "IDscCircuitVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDscCircuitVerifier>;
    deployContract(
      name: "IIdentityRegistryV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistryV1>;
    deployContract(
      name: "IIdentityVerificationHubV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityVerificationHubV1>;
    deployContract(
      name: "IRegisterCircuitVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegisterCircuitVerifier>;
    deployContract(
      name: "IVcAndDiscloseCircuitVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVcAndDiscloseCircuitVerifier>;
    deployContract(
      name: "CircuitAttributeHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CircuitAttributeHandler>;
    deployContract(
      name: "Formatter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Formatter>;
    deployContract(
      name: "IdentityRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistry>;
    deployContract(
      name: "IdentityRegistryImplV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistryImplV1>;
    deployContract(
      name: "IdentityRegistryStorageV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistryStorageV1>;
    deployContract(
      name: "AirdropToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AirdropToken>;
    deployContract(
      name: "TestCircuitAttributeHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestCircuitAttributeHandler>;
    deployContract(
      name: "TestFormatter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestFormatter>;
    deployContract(
      name: "MockImplRoot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockImplRoot>;
    deployContract(
      name: "ImplRoot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ImplRoot>;
    deployContract(
      name: "ProxyRoot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProxyRoot>;
    deployContract(
      name: "Verifier_vc_and_disclose",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_vc_and_disclose>;
    deployContract(
      name: "Verifier_dsc_sha1_ecdsa_brainpoolP256r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha1_ecdsa_brainpoolP256r1>;
    deployContract(
      name: "Verifier_dsc_sha1_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha1_rsa_65537_4096>;
    deployContract(
      name: "Verifier_dsc_sha256_ecdsa_brainpoolP256r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_brainpoolP256r1>;
    deployContract(
      name: "Verifier_dsc_sha256_ecdsa_secp256r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_secp256r1>;
    deployContract(
      name: "Verifier_dsc_sha256_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsa_65537_4096>;
    deployContract(
      name: "Verifier_dsc_sha256_rsapss_3_32_3072",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_3_32_3072>;
    deployContract(
      name: "Verifier_dsc_sha256_rsapss_65537_32_3072",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_3072>;
    deployContract(
      name: "Verifier_dsc_sha256_rsapss_65537_32_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_4096>;
    deployContract(
      name: "Verifier_register_sha1_sha1_sha1_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha1_sha1_sha1_rsa_65537_4096>;
    deployContract(
      name: "Verifier_register_sha1_sha256_sha256_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha1_sha256_sha256_rsa_65537_4096>;
    deployContract(
      name: "Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1>;
    deployContract(
      name: "Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsa_3_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_3_4096>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_65537_4096>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072>;
    deployContract(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1>;
    deployContract(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1>;
    deployContract(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1>;
    deployContract(
      name: "Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1>;
    deployContract(
      name: "Verifier_register_sha512_sha512_sha512_rsa_65537_4096",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_rsa_65537_4096>;
    deployContract(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;

    deployContract(
      name: "Ownable2StepUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2StepUpgradeable>;
    deployContract(
      name: "OwnableUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUpgradeable>;
    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "UUPSUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeable>;
    deployContract(
      name: "ContextUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ContextUpgradeable>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1822Proxiable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC1967",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Proxy>;
    deployContract(
      name: "ERC1967Utils",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Utils>;
    deployContract(
      name: "Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "Address",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "MerkleProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleProof>;
    deployContract(
      name: "Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "PassportAirdropRoot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PassportAirdropRoot>;
    deployContract(
      name: "Airdrop",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Airdrop>;
    deployContract(
      name: "IdentityVerificationHub",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityVerificationHub>;
    deployContract(
      name: "IdentityVerificationHubImplV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityVerificationHubImplV1>;
    deployContract(
      name: "IdentityVerificationHubStorageV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityVerificationHubStorageV1>;
    deployContract(
      name: "IDscCircuitVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDscCircuitVerifier>;
    deployContract(
      name: "IIdentityRegistryV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistryV1>;
    deployContract(
      name: "IIdentityVerificationHubV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityVerificationHubV1>;
    deployContract(
      name: "IRegisterCircuitVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegisterCircuitVerifier>;
    deployContract(
      name: "IVcAndDiscloseCircuitVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVcAndDiscloseCircuitVerifier>;
    deployContract(
      name: "CircuitAttributeHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CircuitAttributeHandler>;
    deployContract(
      name: "Formatter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Formatter>;
    deployContract(
      name: "IdentityRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistry>;
    deployContract(
      name: "IdentityRegistryImplV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistryImplV1>;
    deployContract(
      name: "IdentityRegistryStorageV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistryStorageV1>;
    deployContract(
      name: "AirdropToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AirdropToken>;
    deployContract(
      name: "TestCircuitAttributeHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestCircuitAttributeHandler>;
    deployContract(
      name: "TestFormatter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestFormatter>;
    deployContract(
      name: "MockImplRoot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockImplRoot>;
    deployContract(
      name: "ImplRoot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ImplRoot>;
    deployContract(
      name: "ProxyRoot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProxyRoot>;
    deployContract(
      name: "Verifier_vc_and_disclose",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_vc_and_disclose>;
    deployContract(
      name: "Verifier_dsc_sha1_ecdsa_brainpoolP256r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha1_ecdsa_brainpoolP256r1>;
    deployContract(
      name: "Verifier_dsc_sha1_rsa_65537_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha1_rsa_65537_4096>;
    deployContract(
      name: "Verifier_dsc_sha256_ecdsa_brainpoolP256r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_brainpoolP256r1>;
    deployContract(
      name: "Verifier_dsc_sha256_ecdsa_secp256r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_ecdsa_secp256r1>;
    deployContract(
      name: "Verifier_dsc_sha256_rsa_65537_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsa_65537_4096>;
    deployContract(
      name: "Verifier_dsc_sha256_rsapss_3_32_3072",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_3_32_3072>;
    deployContract(
      name: "Verifier_dsc_sha256_rsapss_65537_32_3072",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_3072>;
    deployContract(
      name: "Verifier_dsc_sha256_rsapss_65537_32_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_dsc_sha256_rsapss_65537_32_4096>;
    deployContract(
      name: "Verifier_register_sha1_sha1_sha1_rsa_65537_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha1_sha1_sha1_rsa_65537_4096>;
    deployContract(
      name: "Verifier_register_sha1_sha256_sha256_rsa_65537_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha1_sha256_sha256_rsa_65537_4096>;
    deployContract(
      name: "Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha224_sha224_sha224_ecdsa_brainpoolP224r1>;
    deployContract(
      name: "Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha224_sha224_ecdsa_secp224r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP256r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_brainpoolP384r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp256r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_ecdsa_secp384r1>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsa_3_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_3_4096>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsa_65537_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsa_65537_4096>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_3_32_2048>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_2048>;
    deployContract(
      name: "Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha256_sha256_sha256_rsapss_65537_32_3072>;
    deployContract(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP384r1>;
    deployContract(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_brainpoolP512r1>;
    deployContract(
      name: "Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha384_sha384_sha384_ecdsa_secp384r1>;
    deployContract(
      name: "Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_ecdsa_brainpoolP512r1>;
    deployContract(
      name: "Verifier_register_sha512_sha512_sha512_rsa_65537_4096",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier_register_sha512_sha512_sha512_rsa_65537_4096>;
    deployContract(
      name: "PoseidonT3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
