/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface PassportAirdropRootInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "UserIdentifierRegistered"): EventFragment;
}

export namespace UserIdentifierRegisteredEvent {
  export type InputTuple = [
    registeredUserIdentifier: BigNumberish,
    nullifier: BigNumberish
  ];
  export type OutputTuple = [
    registeredUserIdentifier: bigint,
    nullifier: bigint
  ];
  export interface OutputObject {
    registeredUserIdentifier: bigint;
    nullifier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PassportAirdropRoot extends BaseContract {
  connect(runner?: ContractRunner | null): PassportAirdropRoot;
  waitForDeployment(): Promise<this>;

  interface: PassportAirdropRootInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "UserIdentifierRegistered"
  ): TypedContractEvent<
    UserIdentifierRegisteredEvent.InputTuple,
    UserIdentifierRegisteredEvent.OutputTuple,
    UserIdentifierRegisteredEvent.OutputObject
  >;

  filters: {
    "UserIdentifierRegistered(uint256,uint256)": TypedContractEvent<
      UserIdentifierRegisteredEvent.InputTuple,
      UserIdentifierRegisteredEvent.OutputTuple,
      UserIdentifierRegisteredEvent.OutputObject
    >;
    UserIdentifierRegistered: TypedContractEvent<
      UserIdentifierRegisteredEvent.InputTuple,
      UserIdentifierRegisteredEvent.OutputTuple,
      UserIdentifierRegisteredEvent.OutputObject
    >;
  };
}
