/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdropTokenSol from "./airdropToken.sol";
export type { airdropTokenSol };
import type * as testCircuitAttributeHandlerSol from "./testCircuitAttributeHandler.sol";
export type { testCircuitAttributeHandlerSol };
import type * as testFormatterSol from "./testFormatter.sol";
export type { testFormatterSol };
import type * as testImplRootSol from "./testImplRoot.sol";
export type { testImplRootSol };
