/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as disclose from "./disclose";
export type { disclose };
import type * as dsc from "./dsc";
export type { dsc };
import type * as register from "./register";
export type { register };
