/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ImplRoot__factory } from "./ImplRoot__factory";
export { ProxyRoot__factory } from "./ProxyRoot__factory";
