/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IdentityRegistryImplV1__factory } from "./IdentityRegistryImplV1__factory";
export { IdentityRegistryStorageV1__factory } from "./IdentityRegistryStorageV1__factory";
