/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdentityRegistryImplV1 } from "./IdentityRegistryImplV1";
export type { IdentityRegistryStorageV1 } from "./IdentityRegistryStorageV1";
