/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as identityRegistryImplV1Sol from "./IdentityRegistryImplV1.sol";
export type { identityRegistryImplV1Sol };
export type { IdentityRegistry } from "./IdentityRegistry";
